export const navigationSections = [
  {
    title: "Workspace",
    items: [
      { href: "/dashboard", label: "Dashboard", note: "overview", short: "DB" },
      { href: "/domains", label: "Domains", note: "verification", short: "DM" },
      { href: "/credentials", label: "Credentials", note: "smtp access", short: "CR" },
      { href: "/logs", label: "Logs", note: "event stream", short: "LG" },
      { href: "/suppressions", label: "Suppressions", note: "recipient safety", short: "SP" },
      { href: "/billing", label: "Billing", note: "plans and invoices", short: "BL" },
      { href: "/usage", label: "Usage", note: "quota posture", short: "US" },
      { href: "/deliverability", label: "Deliverability", note: "health indicators", short: "DV" },
      { href: "/alerts", label: "Alerts", note: "customer center", short: "AT" },
      { href: "/settings", label: "Settings", note: "org status", short: "ST" },
      { href: "/domains/new", label: "New Domain", note: "wizard", short: "NW" },
    ],
  },
  {
    title: "Admin",
    items: [
      { href: "/admin/overview", label: "Overview", note: "operator view", short: "OV" },
      { href: "/admin/organizations", label: "Organizations", note: "customers", short: "OR" },
      { href: "/admin/billing", label: "Plans", note: "catalog", short: "PL" },
      { href: "/admin/payments", label: "Payments", note: "manual review", short: "PY" },
      { href: "/admin/invoices", label: "Invoices", note: "status control", short: "IV" },
      { href: "/admin/usage", label: "Usage", note: "org quotas", short: "UG" },
      { href: "/admin/deliverability", label: "Deliverability", note: "global posture", short: "DL" },
      { href: "/admin/domain-health", label: "Domain Health", note: "dns snapshots", short: "DH" },
      { href: "/admin/alerts", label: "Alerts", note: "resolve center", short: "AR" },
      { href: "/admin/retention", label: "Retention", note: "cleanup rules", short: "RT" },
      { href: "/admin/audit-logs", label: "Audit Logs", note: "trail", short: "AU" },
      { href: "/admin/logs", label: "Admin Logs", note: "global search", short: "AL" },
      { href: "/admin/system", label: "System", note: "health and guardrails", short: "SY" },
    ],
  },
];
